version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DummyPassword
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/receipt-calendar
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres: