default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: DummyPassword
  pool: 5

production:
  <<: *default
  database: receipt_calendar

development:
  <<: *default
  database: receipt_calendar_dev

test:
  <<: *default
  database: receipt_calendar_test
